Repository approvers/change-status-go, pull requests merged in 2020-07, with the labels that each got.

#20 [fix]環境変数で読み込むようにした(はず)
  .gitignore
  main.go
Labels: enhancement

#19 Refactor
  .gitignore
  main.go
  src/decodeMorse.go
  src/fecthMessage.go
  src/message.go
  src/sendImage.go
  src/tools.go
Labels: bug, enhancement

#26 DockerfileのイメージをScratchをAlpineに変更
  Dockerfile
Labels: bug
